class LangData{
  String name;
  String engName;
  String image;
  bool current;
  int id;
  LangData({this.name, this.engName, this.image, this.current, this.id});
}

class Lang {

  static var english = 1;
  static var german = 2;
  static var espanol = 3;
  static var french = 4;
  static var korean = 5;

  List<LangData> langData = [
    LangData(name: "English", engName: "English", image: "assets/usa.png", current: false, id: english),
    LangData(name: "German", engName: "Deutsh", image: "assets/ger.png", current: false, id: german),
    LangData(name: "Spanish", engName: "Spana", image: "assets/esp.png", current: false, id: espanol),
    LangData(name: "French", engName: "French", image: "assets/fra.png", current: false, id: french),
    LangData(name: "Korean", engName: "Korean", image: "assets/kor.png", current: false, id: korean),
  ];

  Map<int, String> langKorean = {
    0: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    1 : "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    2 : "Lorem ipsum",
    3 : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ",
    10 : "Food Delivery Boy Flutter App UI Kit",
    11 : "계정이 없으십니까? 생성",
    12 : "비밀번호 분실",
    13 : "로그인부터 시작하겠습니다!",
    14 : "로그인",
    15 : "비밀번호",
    16 : "로그인",
    17 : "비밀번호 분실",
    18 : "이메일 주소",
    19 : "보내기",
    20 : "계정 만들기!",
    21 : "로그인",
    22 : "비밀번호 확인",
    23 : "계정 생성",
    24 : "주문",
    25 : "알림",
    26 : "도움말 및 지원",
    27 : "계정",
    28 : "언어",
    29 : "로그 아웃",
    30 : "앱 언어",
    31 : "로그 아웃",
    32 : "사용자 이름",
    33 : "이메일",
    34 : "제품",
    35 : "서비스",
    36 : "배달",
    37 : "기타",
    38 : "도움말 및 지원",
    39 : "알림 없음",
    40 : "삭제하려면 알림을 왼쪽으로 스 와이프하세요.",
    41 : "신규",
    42 : "활성",
    43 : "역사",
    44 : "주문 ID",
    45 : "날짜",
    46 : "거리",
    47 : "지도에서",
    48 : "수락",
    49 : "km",
    50 : "주문 없음",
    51 : "완료",
    52 : "고객 이름",
    53 : "고객 전화",
    54 : "고객에게 전화",
    55 : "주문으로 돌아 가기",
    56 : "주문 정보",
    57 : "소계",
    58 : "쇼핑 비용",
    59 : "세금",
    60 : "합계",
    61 : "지도로 돌아 가기",
    62 : "온라인 / 오프라인",
    63 : "전화",
    64 : "프로필 편집",
    65 : "저장",
    66 : "취소",
    67 : "사용자 이름 입력",
    68 : "사용자 이메일 입력",
    69 : "사용자 전화 번호 입력",
    70 : "비밀번호 변경",
    71 : "변경",
    72 : "이전 비밀번호",
    73 : "이전 비밀번호 입력",
    74 : "새 비밀번호",
    75 : "새 비밀번호 입력",
    76 : "새 비밀번호 확인",
    77 : "갤러리 열기",
    78 : "카메라 열기",
    79 : "통계",
    80 : "수입",
    81 : "주",
    82 : "월",
    83 : "수입",
    84 : "거부",
    85 : "거부 이유",
    86 : "보내기",
    87 : "이유 입력",
    88 : "여기",
    89 : "지도",
  };

  Map<int, String> langFrench = {
    0: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    1 : "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    2 : "Lorem ipsum",
    3 : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ",
    10 : "Food Delivery Boy Flutter App UI Kit",
    11: "Vous n'avez pas de compte? Créer",
    12: "Mot de passe oublié",
    13: "Commençons par LogIn!",
    14: "Connexion",
    15: "Mot de passe",
    16: "LOGIN",
    17: "Mot de passe oublié",
    18: "Adresse e-mail",
    19: "ENVOYER",
    20: "Créez un compte!",
    21: "Connexion",
    22: "Confirmer le mot de passe",
    23: "CRÉER UN COMPTE",
    24: "Ordres",
    25: "Notifications",
    26: "Aide et support",
    27: "Compte",
    28: "Langues",
    29: "Déconnexion",
    30: "Langue de l'application",
    31: "Déconnexion",
    32: "Nom d'utilisateur",
    33: "E-mail",
    34: "Produits",
    35: "Services",
    36: "Livraison",
    37: "Divers",
    38: "Aide et support",
    39: "Je n'ai pas de notifications",
    40: "Faites glisser la notification vers la gauche pour la supprimer",
    41: "Nouveau",
    42: "Actif",
    43: "Histoire",
    44: "ID de commande",
    45: "Date",
    46: "Distance",
    47: "Sur la carte",
    48: "Accepter",
    49: "km",
    50: "Je n'ai pas de commandes",
    51: "Terminé",
    52: "Nom du client",
    53: "Téléphone client",
    54: "Appel au client",
    55: "Retour aux commandes",
    56: "Détails de la commande",
    57: "Sous-total",
    58: "Frais d'achat",
    59: "Taxes",
    60: "Total",
    61: "Retour à la carte",
    62: "En ligne / Hors ligne",
    63: "Téléphone",
    64: "Modifier le profil",
    65: "Enregistrer",
    66: "Annuler",
    67: "Entrez votre nom d'utilisateur",
    68: "Entrez votre adresse e-mail utilisateur",
    69: "Entrez votre téléphone utilisateur",
    70: "Changer le mot de passe",
    71: "Changer",
    72: "Ancien mot de passe",
    73: "Entrez votre ancien mot de passe",
    74: "Nouveau mot de passe",
    75: "Entrez votre nouveau mot de passe",
    76: "Confirmer le nouveau mot de passe",
    77: "Ouvrir la galerie",
    78: "Ouvrir la caméra",
    79: "Statistiques",
    80: "Gains",
    81: "semaine",
    82: "mois",
    83: "Gagner",
    84: "Rejet",
    85: "Raison du rejet",
    86: "Envoyer",
    87: "Entrez la raison",
    88: "ici",
    89: "Carte",
  };

  Map<int, String> langDeu = {
    0 : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    1 : "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    2 : "Lorem ipsum",
    3 : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ",
    10 : "Food Delivery Boy Flutter App UI Kit",
    11: "Sie haben noch kein Konto? Erstellen",
    12: "Passwort vergessen",
    13: "Beginnen wir mit LogIn!",
    14: "Login",
    15: "Passwort",
    16: "LOGIN",
    17: "Passwort vergessen",
    18: "E-Mail-Adresse",
    19: "SENDEN",
    20: "Konto erstellen!",
    21: "Login",
    22: "Passwort bestätigen",
    23: "KONTO ERSTELLEN",
    24: "Bestellungen",
    25: "Benachrichtigungen",
    26: "Hilfe & Support",
    27: "Konto",
    28: "Sprachen",
    29: "Abmelden",
    30: "App Language",
    31: "Abmelden",
    32: "Benutzername",
    33: "E-Mail",
    34: "Produkte",
    35: "Dienstleistungen",
    36: "Lieferung",
    37: "Verschiedenes",
    38: "Hilfe & Support",
    39: "Keine Benachrichtigungen haben",
    40: "Wischen Sie die Benachrichtigung nach links, um sie zu löschen",
    41: "Neu",
    42: "Aktiv",
    43: "Geschichte",
    44: "Bestellnummer",
    45: "Datum",
    46: "Entfernung",
    47: "Auf Karte",
    48: "Akzeptieren",
    49: "km",
    50: "Keine Bestellungen haben",
    51: "Vollständig",
    52: "Kundenname",
    53: "Kundentelefon",
    54: "Anruf beim Kunden",
    55: "Zurück zu Bestellungen",
    56: "Bestelldetails",
    57: "Zwischensumme",
    58: "Einkaufskosten",
    59: "Steuern",
    60: "Gesamt",
    61: "Zurück zur Karte",
    62: "Online / Offline",
    63: "Telefon",
    64: "Profil bearbeiten",
    65: "Speichern",
    66: "Abbrechen",
    67: "Geben Sie Ihren Benutzernamen ein",
    68: "Geben Sie Ihre Benutzer-E-Mail-Adresse ein",
    69: "Geben Sie Ihr Benutzertelefon ein",
    70: "Passwort ändern",
    71: "Ändern",
    72: "Altes Passwort",
    73: "Geben Sie Ihr altes Passwort ein",
    74: "Neues Passwort",
    75: "Geben Sie Ihr neues Passwort ein",
    76: "Neues Passwort bestätigen",
    77: "Galerie öffnen",
    78: "Kamera öffnen",
    79: "Statistik",
    80: "Einnahmen",
    81: "Woche",
    82: "Monat",
    83: "Verdienen",
    84: "Ablehnung",
    85: "Grund zur Ablehnung",
    86: "Senden",
    87: "Grund eingeben",
    88: "hier",
    89: "Karte",
  };

  Map<int, String> langEsp = {
    0 : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    1 : "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    2 : "Lorem ipsum",
    3 : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ",
    10 : "Food Delivery Boy Flutter App UI Kit",
    11: "¿No tienes una cuenta? Crear",
    12: "Contraseña olvidada",
    13: "¡Empecemos con Iniciar sesión!",
    14: "Iniciar sesión",
    15: "Contraseña",
    16: "INICIAR SESIÓN",
    17: "Contraseña olvidada",
    18: "Dirección de correo electrónico",
    19: "ENVIAR",
    20: "¡Crea una cuenta!",
    21: "Iniciar sesión",
    22: "Confirmar contraseña",
    23: "CREAR CUENTA",
    24: "Pedidos",
    25: "Notificaciones",
    26: "Ayuda y soporte técnico",
    27: "Cuenta",
    28: "Idiomas",
    29: "Cerrar sesión",
    30: "Idioma de la aplicación",
    31: "Cerrar sesión",
    32: "Nombre de usuario",
    33: "Correo electrónico",
    34: "Productos",
    35: "Servicios",
    36: "Entrega",
    37: "Varios",
    38: "Ayuda y soporte",
    39: "No tener notificaciones",
    40: "Desliza hacia la izquierda la notificación para eliminarla",
    41: "Nuevo",
    42: "Activo",
    43: "Historia",
    44: "ID de pedido",
    45: "Fecha",
    46: "Distancia",
    47: "En el mapa",
    48: "Aceptar",
    49: "km",
    50: "No tener pedidos",
    51: "Completo",
    52: "Nombre del cliente",
    53: "Teléfono del cliente",
    54: "Llamar al cliente",
    55: "Volver a pedidos",
    56: "Detalles del pedido",
    57: "Subtotal",
    58: "Costos de compra",
    59: "Impuestos",
    60: "Total",
    61: "Volver al mapa",
    62: "En línea / Fuera de línea",
    63: "Teléfono",
    64: "Editar perfil",
    65: "Guardar",
    66: "Cancelar",
    67: "Introduzca su nombre de usuario",
    68: "Introduzca su correo electrónico de usuario",
    69: "Ingrese su teléfono de usuario",
    70: "Cambiar contraseña",
    71: "Cambiar",
    72: "Contraseña anterior",
    73: "Ingrese su contraseña anterior",
    74: "Nueva contraseña",
    75: "Ingrese su nueva contraseña",
    76: "Confirmar nueva contraseña",
    77: "Abrir galería",
    78: "Cámara abierta",
    79: "Estadísticas",
    80: "Ingresos",
    81: "semana",
    82: "mes",
    83: "Ganancia",
    84: "Rechazo",
    85: "Razón para rechazar",
    86: "Enviar",
    87: "Ingrese el motivo",
    88: "aquí",
    89: "Mapa",
  };

  Map<int, String> langEng = {
    0 : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    1 : "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    2 : "Lorem ipsum",
    3 : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ",
    10 : "Food Delivery Boy Flutter App UI Kit",
    11 : "Don't have an account? Create",
    12 : "Forgot password",
    13 : "Let's start with LogIn!",
    14 : "Login",
    15 : "Password",
    16 : "LOGIN",
    17 : "Forgot password",
    18 : "E-mail address",
    19 : "SEND",
    20 : "Create an Account!",
    21 : "Login",
    22 : "Confirm Password",
    23 : "CREATE ACCOUNT",
    24 : "Orders",
    25 : "Notifications",
    26 : "Help & Support",
    27 : "Account",
    28 : "Languages",
    29 : "Sign Out",
    30 : "App Language",
    31 : "Log Out",
    32 : "User Name",
    33 : "E-mail",
    34 : "Products",
    35 : "Services",
    36 : "Delivery",
    37 : "Misc",
    38 : "Help & support",
    39 : "Not Have Notifications",
    40 : "This is very important information",
    41 : "New",
    42 : "Active",
    43 : "History",
    44 : "Order ID",
    45 : "Date",
    46 : "Distance",
    47 : "On Map",
    48 : "Accept",
    49 : "km",
    50 : "Not Have Orders",
    51 : "Complete",
    52 : "Customer name",
    53 : "Customer phone",
    54 : "Call to Customer",
    55 : "Back to Orders",
    56 : "Order Details",
    57 : "Subtotal",
    58 : "Shopping costs",
    59 : "Taxes",
    60 : "Total",
    61 : "Back to Map",
    62 : "Online/Offline",
    63 : "Phone",
    64 : "Edit profile",
    65 : "Save",
    66 : "Cancel",
    67 : "Enter your User Name",
    68 : "Enter your User E-mail",
    69 : "Enter your User Phone",
    70 : "Change password",
    71 : "Change",
    72 : "Old password",
    73 : "Enter your old password",
    74 : "New password",
    75 : "Enter your new password",
    76 : "Confirm New password",
    77 : "Open Gallery",
    78 : "Open Camera",
    79 : "Statistics",
    80 : "Earnings",
    81 : "week",
    82 : "month",
    83 : "Earning",
    84 : "Rejection",
    85 : "Reason to Reject",
    86 : "Send",
    87 : "Enter Reason",
    88 : "here",
    89 : "Map",

  };

  //
  //
  //
  setLang(int id){
    if (id == english) {
      defaultLang = langEng;
      init = true;
    }
    if (id == german) {
      defaultLang = langDeu;
      init = true;
    }
    if (id == espanol) {
      defaultLang = langEsp;
      init = true;
    }
    if (id == french) {
      defaultLang = langFrench;
      init = true;
    }
    if (id == korean) {
      defaultLang = langKorean;
      init = true;
    }
    for (var lang in langData) {
      lang.current = false;
      if (lang.id == id)
        lang.current = true;
    }
  }

  Map<int, String> defaultLang;
  var init = false;

  String get(int id){
    if (!init) return "";
    return defaultLang[id];
  }

}

